name: Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coverage:
    name: Collect coverage report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Run Tests
        run: |
          npm run clean
          npm ci
          npm run test:coverage

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
